import { StyleSheet } from "react-native";

export default StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: "center",
    padding: 24,
    backgroundColor: "#f9f9f9",
    alignItems: "center",
  },
  card: {
    width: "100%",
    maxWidth: 400,
    backgroundColor: "#fff",
    borderRadius: 22,
    padding: 28,
    shadowColor: "#228B22",
    shadowOpacity: 0.07,
    shadowRadius: 16,
    elevation: 8,
    alignItems: "center",
  },
  logo: {
    fontSize: 54,
    marginBottom: 14,
    color: "#228B22",
    textAlign: "center",
  },
  title: {
    fontSize: 32,
    fontWeight: "bold",
    color: "#228B22",
    marginBottom: 6,
    textAlign: "center",
  },
  subtitle: {
    fontSize: 20,
    color: "#444",
    marginBottom: 18,
    textAlign: "center",
    fontWeight: "500",
  },
  input: {
    width: "100%",
    backgroundColor: "#f6f6f6",
    borderRadius: 14,
    padding: 15,
    fontSize: 17,
    color: "#222",
    borderWidth: 1,
    borderColor: "#90ee90",
    marginBottom: 15,
    shadowColor: "#ddd",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
  },
  button: {
    backgroundColor: "#228B22",
    borderRadius: 22,
    paddingVertical: 16,
    paddingHorizontal: 24,
    alignItems: "center",
    marginTop: 8,
    width: "100%",
    elevation: 3,
    shadowColor: "#228B22",
    shadowOpacity: 0.14,
    shadowRadius: 6,
  },
  buttonText: {
    color: "#fff",
    fontSize: 19,
    fontWeight: "bold",
    letterSpacing: 1.1,
  },
  switchText: {
    color: "#228B22",
    textAlign: "center",
    marginTop: 24,
    fontSize: 16,
    textDecorationLine: "underline",
    fontWeight: "600",
  },
  error: {
    color: "#b71c1c",
    backgroundColor: "#ffeeee",
    padding: 9,
    borderRadius: 10,
    marginBottom: 13,
    textAlign: "center",
    width: "100%",
  },
});