import { StyleSheet, Dimensions } from "react-native";
const { width, height } = Dimensions.get("window");

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#f9f9f9",
    paddingTop: 16,
  },
  header: {
    backgroundColor: "#228B22",
    paddingVertical: 18,
    paddingHorizontal: 22,
    borderBottomLeftRadius: 18,
    borderBottomRightRadius: 18,
    alignItems: "center",
    marginBottom: 8,
    flexDirection: "row",
    justifyContent: "space-between",
  },
  headerTitle: {
    fontSize: 23,
    fontWeight: "bold",
    color: "#fff",
    letterSpacing: 1.2,
    flex: 1,
    textAlign: "center",
  },
  closeBtn: {
    position: "absolute",
    right: 18,
    top: 14,
    zIndex: 10,
    backgroundColor: "#FFD700",
    borderRadius: 16,
    padding: 8,
    elevation: 6,
  },
  closeBtnText: {
    fontSize: 22,
    color: "#228B22",
    fontWeight: "bold",
  },
  // Matches list
  matchesList: {
    flex: 1,
    paddingHorizontal: 16,
    paddingTop: 6,
  },
  matchCard: {
    backgroundColor: "#fff",
    borderRadius: 18,
    padding: 18,
    marginBottom: 12,
    flexDirection: "row",
    alignItems: "center",
    elevation: 4,
    shadowColor: "#228B22",
    shadowOpacity: 0.08,
    shadowRadius: 7,
    shadowOffset: { width: 0, height: 3 },
  },
  matchAvatar: {
    width: 54,
    height: 54,
    borderRadius: 27,
    backgroundColor: "#eee",
    marginRight: 16,
    borderWidth: 2,
    borderColor: "#90ee90",
  },
  matchInfo: {
    flex: 1,
    justifyContent: "center",
  },
  matchName: {
    fontSize: 17,
    fontWeight: "bold",
    color: "#228B22",
  },
  matchHandicap: {
    fontSize: 15,
    color: "#FFD700",
    fontWeight: "600",
    marginBottom: 3,
  },
  matchBio: {
    fontSize: 14,
    color: "#444",
  },
  chatBtn: {
    backgroundColor: "#FFD700",
    borderRadius: 14,
    paddingVertical: 8,
    paddingHorizontal: 18,
    alignItems: "center",
    marginLeft: 10,
    elevation: 2,
  },
  chatBtnText: {
    color: "#228B22",
    fontWeight: "bold",
    fontSize: 16,
  },
  // Chat styles
  chatContainer: {
    flex: 1,
    backgroundColor: "#f9f9f9",
    paddingHorizontal: 16,
    paddingTop: 10,
    paddingBottom: 12,
  },
  chatBubbleRow: {
    flexDirection: "row",
    marginBottom: 12,
    alignItems: "flex-end",
  },
  chatBubble: {
    maxWidth: width * 0.7,
    paddingVertical: 10,
    paddingHorizontal: 15,
    borderRadius: 18,
    backgroundColor: "#228B22",
    marginRight: 8,
    elevation: 2,
    shadowColor: "#228B22",
    shadowOpacity: 0.10,
    shadowRadius: 2,
  },
  chatBubbleSelf: {
    backgroundColor: "#FFD700",
    marginLeft: "auto",
    marginRight: 0,
  },
  chatBubbleText: {
    color: "#fff",
    fontSize: 16,
    fontWeight: "500",
  },
  chatBubbleTextSelf: {
    color: "#228B22",
    fontWeight: "bold",
  },
  chatInputRow: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 4,
    paddingVertical: 8,
    borderTopWidth: 1,
    borderColor: "#90ee90",
    backgroundColor: "#fff",
    borderRadius: 14,
    marginBottom: 8,
    elevation: 2,
    shadowColor: "#228B22",
    shadowOpacity: 0.07,
    shadowRadius: 3,
  },
  chatInput: {
    flex: 1,
    minHeight: 40,
    fontSize: 16,
    paddingHorizontal: 12,
    color: "#222",
    backgroundColor: "#f6f6f6",
    borderRadius: 12,
    marginRight: 10,
  },
  sendBtn: {
    backgroundColor: "#228B22",
    borderRadius: 16,
    paddingVertical: 10,
    paddingHorizontal: 16,
    alignItems: "center",
  },
  sendBtnText: {
    color: "#fff",
    fontWeight: "bold",
    fontSize: 17,
  },
});