import { StyleSheet, Dimensions } from "react-native";
const { width } = Dimensions.get("window");

export default StyleSheet.create({
  container: { flex: 1 },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingTop: 50,
    paddingHorizontal: 16,
    paddingBottom: 16,
  },
  backBtn: { padding: 8 },
  headerTitle: { fontSize: 24, fontWeight: "800", color: "#fff" },
  messageList: { padding: 20, paddingBottom: 10 },
  bubbleRow: { marginVertical: 6, flexDirection: "row" },
  bubbleRowRight: { justifyContent: "flex-end" },
  bubble: {
    maxWidth: width * 0.75,
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 20,
    backgroundColor: "rgba(34,197,94,0.15)",
    borderWidth: 1,
    borderColor: "#22c55e33",
  },
  bubbleMine: {
    backgroundColor: "#22c55e",
  },
  bubbleText: { color: "#fff", fontSize: 16, lineHeight: 22 },
  bubbleTextMine: { color: "#fff", fontWeight: "600" },
  bubbleFooter: { flexDirection: "row", alignItems: "center", marginTop: 4, gap: 6, opacity: 0.8 },
  bubbleTime: { fontSize: 11, color: "#e2e8f0" },

  gameCard: {
    backgroundColor: "rgba(34,197,94,0.2)",
    borderRadius: 20,
    padding: 20,
    marginVertical: 16,
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#22c55e",
    alignSelf: "center",
    maxWidth: width * 0.85,
  },
  gameTitle: { fontSize: 20, fontWeight: "bold", color: "#22c55e", marginVertical: 8 },
  gameDetail: { fontSize: 16, color: "#cbd5e1", marginVertical: 2 },
  gameValue: { color: "#fff", fontWeight: "600" },
  gameOrganizer: { marginTop: 12, fontSize: 14, color: "#94a3b8", fontStyle: "italic" },

  inputContainer: {
    flexDirection: "row",
    padding: 16,
    paddingTop: 8,
    alignItems: "center",
    backgroundColor: "rgba(15,23,42,0.8)",
    borderTopWidth: 1,
    borderColor: "#334155",
  },
  input: {
    flex: 1,
    backgroundColor: "rgba(255,255,255,0.1)",
    borderRadius: 25,
    paddingHorizontal: 20,
    paddingVertical: 14,
    color: "#fff",
    fontSize: 17,
    marginRight: 12,
  },
  sendBtn: {
    backgroundColor: "#22c55e",
    width: 50,
    height: 50,
    borderRadius: 25,
    justifyContent: "center",
    alignItems: "center",
  },
  bookGameBtn: {
    flexDirection: "row",
    backgroundColor: "rgba(34,197,94,0.3)",
    marginHorizontal: 20,
    marginBottom: 20,
    padding: 16,
    borderRadius: 16,
    justifyContent: "center",
    alignItems: "center",
    gap: 10,
    borderWidth: 1,
    borderColor: "#22c55e",
  },
  bookGameText: { color: "#fff", fontSize: 17, fontWeight: "600" },

  modalOverlay: { flex: 1, backgroundColor: "rgba(0,0,0,0.8)", justifyContent: "center", alignItems: "center" },
  modalContent: {
    backgroundColor: "#1e293b",
    width: "90%",
    borderRadius: 20,
    padding: 24,
    borderWidth: 1,
    borderColor: "#22c55e",
  },
  modalTitle: { fontSize: 24, fontWeight: "bold", color: "#22c55e", textAlign: "center", marginBottom: 24 },
  modalInput: {
    backgroundColor: "rgba(255,255,255,0.1)",
    borderRadius: 12,
    padding: 16,
    color: "#fff",
    marginBottom: 16,
    fontSize: 17,
    borderWidth: 1,
    borderColor: "#334155",
  },
  modalButtons: { flexDirection: "row", justifyContent: "space-between", marginTop: 16 },
  modalCancel: { flex: 1, padding: 16, backgroundColor: "#475569", borderRadius: 12, marginRight: 10, alignItems: "center" },
  modalConfirm: { flex: 1, padding: 16, backgroundColor: "#22c55e", borderRadius: 12, marginLeft: 10, alignItems: "center" },
  modalCancelText: { color: "#fff", fontWeight: "600" },
  modalConfirmText: { color: "#fff", fontWeight: "bold" },
});