import { StyleSheet, Dimensions } from "react-native";
const { width, height } = Dimensions.get("window");

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#f9f9f9",
    paddingTop: 0,
  },
  header: {
    backgroundColor: "#228B22",
    paddingVertical: 18,
    paddingHorizontal: 22,
    borderBottomLeftRadius: 18,
    borderBottomRightRadius: 18,
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "space-between",
    elevation: 6,
    shadowColor: "#228B22",
    shadowOpacity: 0.16,
    shadowRadius: 7,
  },
  headerTitle: {
    fontSize: 22,
    fontWeight: "bold",
    color: "#fff",
    letterSpacing: 1.2,
    flex: 1,
    textAlign: "center",
    marginLeft: 22,
    marginRight: 22,
  },
  closeBtn: {
    backgroundColor: "#FFD700",
    borderRadius: 16,
    padding: 8,
    marginLeft: 6,
    elevation: 4,
  },
  closeBtnText: {
    fontSize: 22,
    color: "#228B22",
    fontWeight: "bold",
  },
  chatContainer: {
    flex: 1,
    paddingHorizontal: 14,
    paddingTop: 10,
    paddingBottom: 8,
    minHeight: 260,
    backgroundColor: "#f9f9f9",
  },
  chatBubbleRow: {
    flexDirection: "row",
    marginBottom: 8,
    alignItems: "flex-end",
  },
  chatBubble: {
    maxWidth: width * 0.7,
    paddingVertical: 11,
    paddingHorizontal: 16,
    borderRadius: 18,
    backgroundColor: "#fff",
    marginRight: 8,
    elevation: 1,
    shadowColor: "#228B22",
    shadowOpacity: 0.10,
    shadowRadius: 2,
    borderWidth: 1,
    borderColor: "#90ee90",
  },
  chatBubbleSelf: {
    backgroundColor: "#FFD700",
    alignSelf: "flex-end",
    borderColor: "#FFD700",
  },
  chatBubbleText: {
    color: "#228B22",
    fontSize: 16,
    fontWeight: "500",
  },
  chatBubbleTextSelf: {
    color: "#228B22",
    fontWeight: "bold",
  },
  chatMeta: {
    color: "#bbb",
    fontSize: 11,
    marginTop: 4,
    textAlign: "right",
  },
  chatInputRow: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 10,
    paddingVertical: 8,
    borderTopWidth: 1,
    borderColor: "#90ee90",
    backgroundColor: "#fff",
    borderRadius: 14,
    marginHorizontal: 10,
    marginBottom: 8,
    elevation: 2,
    shadowColor: "#228B22",
    shadowOpacity: 0.07,
    shadowRadius: 3,
  },
  chatInput: {
    flex: 1,
    minHeight: 40,
    fontSize: 16,
    paddingHorizontal: 12,
    color: "#222",
    backgroundColor: "#f6f6f6",
    borderRadius: 12,
    marginRight: 10,
    borderWidth: 1,
    borderColor: "#90ee90",
  },
  sendBtn: {
    backgroundColor: "#228B22",
    borderRadius: 16,
    paddingVertical: 10,
    paddingHorizontal: 16,
    alignItems: "center",
    elevation: 3,
  },
  sendBtnText: {
    color: "#fff",
    fontWeight: "bold",
    fontSize: 17,
  },
  gameBtn: {
    backgroundColor: "#FFD700",
    borderRadius: 22,
    padding: 14,
    margin: 14,
    alignItems: "center",
    elevation: 2,
  },
  gameBtnText: {
    color: "#228B22",
    fontWeight: "bold",
    fontSize: 16,
  },
  // Golf game form styles
  gameFormOverlay: {
    position: "absolute",
    top: 0, left: 0, right: 0, bottom: 0,
    backgroundColor: "rgba(34,139,34,0.10)",
    justifyContent: "center",
    alignItems: "center",
    zIndex: 100,
  },
  gameForm: {
    width: "88%",
    backgroundColor: "#fff",
    borderRadius: 18,
    padding: 18,
    elevation: 6,
    shadowColor: "#228B22",
    shadowOpacity: 0.13,
    shadowRadius: 8,
    alignItems: "stretch",
  },
  gameFormTitle: {
    fontSize: 20,
    fontWeight: "bold",
    marginBottom: 16,
    color: "#228B22",
    textAlign: "center",
    letterSpacing: 0.8,
  },
  gameInput: {
    borderWidth: 1,
    borderColor: "#FFD700",
    borderRadius: 12,
    padding: 12,
    marginBottom: 12,
    backgroundColor: "#f6f6f6",
    fontSize: 16,
    color: "#222",
  },
  gameFormBtnRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 10,
  },
  organizeBtn: {
    backgroundColor: "#228B22",
    borderRadius: 14,
    padding: 12,
    marginRight: 8,
    flex: 1,
    alignItems: "center",
  },
  organizeText: {
    color: "#fff",
    fontWeight: "bold",
    fontSize: 16,
  },
  cancelBtn: {
    backgroundColor: "#FFD700",
    borderRadius: 14,
    padding: 12,
    flex: 1,
    alignItems: "center",
  },
  cancelText: {
    color: "#228B22",
    fontWeight: "bold",
    fontSize: 16,
  },
  // Golf game card in chat
  gameCard: {
    backgroundColor: "#e6ffe6",
    borderRadius: 18,
    padding: 16,
    marginVertical: 8,
    maxWidth: "70%",
    alignSelf: "center",
    borderWidth: 2,
    borderColor: "#FFD700",
    elevation: 3,
    shadowColor: "#228B22",
    shadowOpacity: 0.10,
    shadowRadius: 5,
  },
  gameCardTitle: {
    color: "#228B22",
    fontWeight: "bold",
    fontSize: 17,
    marginBottom: 8,
    textAlign: "center"
  },
  gameCardDetail: {
    color: "#228B22",
    fontSize: 15,
    marginBottom: 2
  },
  gameCardValue: {
    color: "#444",
    fontWeight: "bold"
  },
  gameCardOrganizer: {
    marginTop: 7,
    fontStyle: "italic",
    color: "#228B22",
    fontSize: 14,
    textAlign: "right"
  },
});