import { StyleSheet, Dimensions } from "react-native";
const { width } = Dimensions.get("window");

export default StyleSheet.create({
  gradientBackground: {
    flex: 1,
    backgroundColor: "#f9f9f9",
  },
  swiperContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    marginTop: 14,
    marginBottom: 86, // Leave space for bottom nav
  },
  card: {
    backgroundColor: "#fff",
    borderRadius: 20,
    padding: 22,
    alignItems: "center",
    shadowColor: "#228B22",
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.15,
    shadowRadius: 16,
    elevation: 8,
    width: width - 48,
    height: 460,
    marginHorizontal: 8,
  },
  imageContainer: {
    width: 260,
    height: 170,
    borderRadius: 16,
    overflow: "hidden",
    marginBottom: 14,
    position: "relative",
    backgroundColor: "#e6ffe6",
    shadowColor: "#228B22",
    shadowOpacity: 0.18,
    shadowRadius: 10,
    elevation: 6,
  },
  cardImage: {
    width: "100%",
    height: "100%",
    borderRadius: 16,
    resizeMode: "cover",
  },
  imageOverlay: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    height: 38,
    backgroundColor: "rgba(34,139,34,0.18)",
    borderBottomLeftRadius: 16,
    borderBottomRightRadius: 16,
  },
  noPhoto: {
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#eee",
  },
  noPhotoText: {
    color: "#999",
    fontSize: 16,
    fontWeight: "600",
  },
  cardTitle: {
    fontSize: 24,
    fontWeight: "bold",
    color: "#228B22",
    marginBottom: 5,
  },
  
  handicapBox: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#FFD700",
    borderRadius: 14,
    paddingVertical: 6,
    paddingHorizontal: 15,
    marginBottom: 7,
    marginTop: 2,
    elevation: 2,
  },
  handicapLabel: {
    fontWeight: "bold",
    color: "#228B22",
    fontSize: 15,
    marginRight: 7,
  },
  handicapValue: {
    color: "#228B22",
    fontWeight: "bold",
    fontSize: 17,
  },
  cardDesc: {
    fontSize: 15,
    color: "#444",
    textAlign: "center",
    marginBottom: 11,
    fontWeight: "500",
  },
  interestsContainer: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "center",
  },
  interestChip: {
    backgroundColor: "#90ee90",
    borderRadius: 12,
    paddingVertical: 5,
    paddingHorizontal: 12,
    margin: 4,
    shadowColor: "#228B22",
    shadowOpacity: 0.10,
    shadowRadius: 3,
    elevation: 2,
  },
  interestText: {
    color: "#228B22",
    fontWeight: "600",
    fontSize: 14,
  },
  noCardsText: {
    textAlign: "center",
    marginTop: 40,
    color: "#888",
    fontSize: 18,
    fontWeight: "500",
  },
  bottomNav: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    backgroundColor: "rgba(240,240,240,0.96)",
    paddingVertical: 10,
    paddingHorizontal: 18,
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
    borderTopLeftRadius: 18,
    borderTopRightRadius: 18,
    shadowColor: "#228B22",
    shadowOffset: { width: 0, height: -2 },
    shadowOpacity: 0.13,
    shadowRadius: 8,
    elevation: 8,
    zIndex: 10,
    minHeight: 72,
    width: "100%",
  },
  navBtn: {
    backgroundColor: "#90ee90",
    borderRadius: 22,
    paddingVertical: 12,
    paddingHorizontal: 24,
    marginHorizontal: 2,
    shadowColor: "#228B22",
    shadowOpacity: 0.16,
    shadowRadius: 6,
    elevation: 3,
  },
  navBtnText: {
    color: "#228B22",
    fontWeight: "bold",
    fontSize: 17,
  },
  profileCircle: {
    backgroundColor: "#fff",
    borderRadius: 100,
    width: 48,
    height: 48,
    justifyContent: "center",
    alignItems: "center",
    marginHorizontal: 8,
    shadowColor: "#000",
    shadowOpacity: 0.12,
    shadowRadius: 4,
    elevation: 4,
    borderWidth: 2,
    borderColor: "#FFD700",
  },
  profileImage: {
    width: 42,
    height: 42,
    borderRadius: 100,
    resizeMode: "cover",
  },
  profilePlaceholder: {
    fontSize: 22,
    color: "#228B22",
    fontWeight: "bold",
  },
  overlayLeft: {
    position: "absolute",
    top: 0,
    left: 0,
    width: width - 48,
    height: 460,
    backgroundColor: "rgba(255, 50, 50, 0.18)",
    borderRadius: 20,
    alignItems: "center",
    justifyContent: "center",
    zIndex: 2,
  },
  overlayLeftLabel: {
    fontSize: 70,
    color: "#ff3333",
    fontWeight: "bold",
    textShadowColor: '#fff',
    textShadowOffset: { width: 1, height: 2 },
    textShadowRadius: 6,
  },
  overlayRight: {
    position: "absolute",
    top: 0,
    left: 0,
    width: width - 48,
    height: 460,
    backgroundColor: "rgba(50,255,50,0.16)",
    borderRadius: 20,
    alignItems: "center",
    justifyContent: "center",
    zIndex: 2,
  },
  overlayRightLabel: {
    fontSize: 70,
    color: "#22bb22",
    fontWeight: "bold",
    textShadowColor: '#fff',
    textShadowOffset: { width: 1, height: 2 },
    textShadowRadius: 6,
  },
});