import { StyleSheet } from "react-native";

export default StyleSheet.create({
  gradientBackground: {
    flex: 1,
    backgroundColor: "#f9f9f9",
  },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    padding: 22,
    paddingTop: 32,
    backgroundColor: "rgba(240,240,240,0.7)",
    borderBottomLeftRadius: 32,
    borderBottomRightRadius: 32,
    shadowColor: "#228B22",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 4,
  },
  logoText: {
    fontSize: 28,
    fontWeight: "bold",
    color: "#228B22",
    fontFamily: "Avenir-Heavy",
    letterSpacing: 1,
  },
  matchesBtn: {
    backgroundColor: "#90ee90",
    borderRadius: 22,
    paddingVertical: 11,
    paddingHorizontal: 18,
    marginRight: 8,
    shadowColor: "#228B22",
    shadowOpacity: 0.16,
    shadowRadius: 6,
    elevation: 3,
  },
  matchesText: {
    color: "#228B22",
    fontWeight: "bold",
    fontSize: 17,
  },
  profileBtn: {
    backgroundColor: "#FFD700",
    borderRadius: 22,
    paddingVertical: 11,
    paddingHorizontal: 18,
    shadowColor: "#FFD700",
    shadowOpacity: 0.18,
    shadowRadius: 6,
    elevation: 3,
  },
  profileText: {
    color: "#228B22",
    fontWeight: "bold",
    fontSize: 17,
  },
  swiperContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    marginTop: 14,
  },
  card: {
    backgroundColor: "#fff",
    borderRadius: 20,
    padding: 22,
    alignItems: "center",
    shadowColor: "#228B22",
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.15,
    shadowRadius: 16,
    elevation: 8,
    width: 340,
    height: 460,
    marginHorizontal: 8,
  },
  imageContainer: {
    width: 260,
    height: 170,
    borderRadius: 16,
    overflow: "hidden",
    marginBottom: 14,
    position: "relative",
    backgroundColor: "#e6ffe6",
    shadowColor: "#228B22",
    shadowOpacity: 0.18,
    shadowRadius: 10,
    elevation: 6,
  },
  cardImage: {
    width: "100%",
    height: "100%",
    borderRadius: 16,
    resizeMode: "cover",
  },
  imageOverlay: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    height: 38,
    backgroundColor: "rgba(34,139,34,0.18)",
    borderBottomLeftRadius: 16,
    borderBottomRightRadius: 16,
  },
  noPhoto: {
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#eee",
  },
  noPhotoText: {
    color: "#999",
    fontSize: 16,
    fontWeight: "600",
  },
  cardTitle: {
    fontSize: 24,
    fontWeight: "bold",
    color: "#228B22",
    marginBottom: 5,
  },
  cardDesc: {
    fontSize: 15,
    color: "#444",
    textAlign: "center",
    marginBottom: 11,
    fontWeight: "500",
  },
  interestsContainer: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "center",
  },
  interestChip: {
    backgroundColor: "#90ee90",
    borderRadius: 12,
    paddingVertical: 5,
    paddingHorizontal: 12,
    margin: 4,
    shadowColor: "#228B22",
    shadowOpacity: 0.10,
    shadowRadius: 3,
    elevation: 2,
  },
  interestText: {
    color: "#228B22",
    fontWeight: "600",
    fontSize: 14,
  },
  noCardsText: {
    textAlign: "center",
    marginTop: 40,
    color: "#888",
    fontSize: 18,
    fontWeight: "500",
  },
});