import { StyleSheet } from "react-native";

export default StyleSheet.create({
  container: {
    flex: 1,
  },
  scrollContent: {
    padding: 24,
    paddingTop: 60,
    paddingBottom: 40,
    alignItems: "center",
  },
  closeBtn: {
    position: "absolute",
    top: 50,
    right: 20,
    zIndex: 10,
    backgroundColor: "rgba(255,255,255,0.15)",
    padding: 10,
    borderRadius: 30,
    backdropFilter: "blur(10px)",
  },
  title: {
    fontSize: 32,
    fontWeight: "800",
    color: "#fff",
    marginBottom: 32,
    letterSpacing: 0.5,
  },
  avatarWrapper: {
    position: "relative",
    marginBottom: 32,
  },
  avatar: {
    width: 140,
    height: 140,
    borderRadius: 70,
    borderWidth: 4,
    borderColor: "#22c55e",
    backgroundColor: "#1e293b",
  },
  cameraOverlay: {
    position: "absolute",
    right: 0,
    bottom: 0,
    backgroundColor: "#22c55e",
    padding: 12,
    borderRadius: 30,
    borderWidth: 4,
    borderColor: "#0f172a",
  },
  inputGroup: {
    width: "100%",
    marginBottom: 24,
  },
  label: {
    color: "#94a3b8",
    fontSize: 14,
    fontWeight: "600",
    marginBottom: 8,
    marginLeft: 4,
    textTransform: "uppercase",
    letterSpacing: 1.2,
  },
  input: {
    backgroundColor: "rgba(255,255,255,0.1)",
    borderRadius: 16,
    padding: 16,
    fontSize: 17,
    color: "#fff",
    borderWidth: 1,
    borderColor: "rgba(34,197,94,0.3)",
  },
  bioInput: {
    height: 100,
    textAlignVertical: "top",
  },
  interestInputRow: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "rgba(255,255,255,0.1)",
    borderRadius: 16,
    paddingHorizontal: 16,
    borderWidth: 1,
    borderColor: "rgba(34,197,94,0.3)",
  },
  interestInput: {
    flex: 1,
    padding: 16,
    fontSize: 17,
    color: "#fff",
  },
  addBtn: {
    padding: 4,
  },
  chipsContainer: {
    flexDirection: "row",
    flexWrap: "wrap",
    marginTop: 12,
    gap: 10,
  },
  chip: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "rgba(34,197,94,0.2)",
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "#22c55e",
    gap: 8,
  },
  chipText: {
    color: "#dcfce7",
    fontWeight: "600",
  },
  saveBtn: {
    backgroundColor: "#22c55e",
    width: "100%",
    paddingVertical: 18,
    borderRadius: 30,
    alignItems: "center",
    marginTop: 20,
    shadowColor: "#22c55e",
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.5,
    shadowRadius: 20,
    elevation: 15,
  },
  saveBtnText: {
    color: "#fff",
    fontSize: 18,
    fontWeight: "bold",
    letterSpacing: 1,
  },
  logoutBtn: {
    marginTop: 20,
    padding: 14,
  },
  logoutText: {
    color: "#ef4444",
    fontSize: 16,
    fontWeight: "600",
  },
});