import { StyleSheet } from "react-native";

export default StyleSheet.create({
  container: {
    padding: 26,
    backgroundColor: "#f9f9f9",
    flexGrow: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  closeBtn: {
    position: "absolute",
    top: 24,
    right: 24,
    zIndex: 10,
    backgroundColor: "#fff",
    borderRadius: 18,
    padding: 8,
    shadowColor: "#228B22",
    shadowOpacity: 0.15,
    shadowRadius: 6,
    elevation: 6,
  },
  closeBtnText: {
    fontSize: 20,
    color: "#228B22",
    fontWeight: "bold",
  },
  title: {
    fontSize: 28,
    fontWeight: "bold",
    color: "#228B22",
    marginBottom: 18,
    marginTop: 18,
    textAlign: "center",
  },
  avatarContainer: {
    alignItems: "center",
    marginBottom: 18,
    marginTop: 10,
  },
  avatarEditBtn: {
    position: "relative",
  },
  avatar: {
    width: 110,
    height: 110,
    borderRadius: 55,
    backgroundColor: "#eee",
    borderWidth: 3,
    borderColor: "#FFD700",
  },
  cameraIcon: {
    position: "absolute",
    right: 0,
    bottom: 0,
    backgroundColor: "#fff",
    borderRadius: 16,
    padding: 6,
    borderWidth: 2,
    borderColor: "#FFD700",
    elevation: 3,
    shadowColor: "#228B22",
    shadowOpacity: 0.15,
    shadowRadius: 5,
  },
  cameraIconText: {
    fontSize: 22,
    color: "#228B22",
  },
  formGroup: {
    width: "100%",
    marginBottom: 18,
  },
  label: {
    fontWeight: "bold",
    color: "#228B22",
    fontSize: 16,
    marginBottom: 7,
    marginLeft: 3,
  },
  input: {
    backgroundColor: "#fff",
    borderRadius: 12,
    padding: 12,
    fontSize: 16,
    color: "#222",
    borderWidth: 1,
    borderColor: "#90ee90",
  },
  interestsRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 9,
  },
  interestInput: {
    flex: 1,
    backgroundColor: "#fff",
    borderRadius: 12,
    padding: 10,
    fontSize: 15,
    color: "#222",
    borderWidth: 1,
    borderColor: "#FFD700",
    marginRight: 8,
  },
  addInterestBtn: {
    backgroundColor: "#FFD700",
    borderRadius: 16,
    padding: 9,
    alignItems: "center",
    justifyContent: "center",
    elevation: 3,
    shadowColor: "#FFD700",
    shadowOpacity: 0.12,
    shadowRadius: 4,
  },
  addInterestBtnText: {
    color: "#228B22",
    fontWeight: "bold",
    fontSize: 22,
  },
  interestChips: {
    flexDirection: "row",
    flexWrap: "wrap",
    marginTop: 7,
  },
  chip: {
    flexDirection: "row",
    backgroundColor: "#90ee90",
    borderRadius: 16,
    paddingVertical: 6,
    paddingHorizontal: 14,
    alignItems: "center",
    margin: 4,
    elevation: 2,
    shadowColor: "#228B22",
    shadowOpacity: 0.08,
    shadowRadius: 3,
  },
  chipText: {
    color: "#228B22",
    fontWeight: "600",
    fontSize: 15,
    marginRight: 7,
  },
  chipRemove: {
    color: "#ff3333",
    fontWeight: "bold",
    fontSize: 18,
  },
  saveBtn: {
    backgroundColor: "#228B22",
    borderRadius: 24,
    paddingVertical: 16,
    paddingHorizontal: 24,
    alignItems: "center",
    marginTop: 18,
    width: "80%",
    elevation: 3,
    shadowColor: "#228B22",
    shadowOpacity: 0.18,
    shadowRadius: 6,
  },
  saveBtnText: {
    color: "#fff",
    fontSize: 18,
    fontWeight: "bold",
    letterSpacing: 1.1,
  },
  logoutBtn: {
    backgroundColor: "#FFD700",
    borderRadius: 24,
    paddingVertical: 13,
    paddingHorizontal: 18,
    alignItems: "center",
    marginTop: 18,
    width: "70%",
    elevation: 2,
    shadowColor: "#FFD700",
    shadowOpacity: 0.11,
    shadowRadius: 4,
  },
  logoutBtnText: {
    color: "#228B22",
    fontWeight: "bold",
    fontSize: 17,
    letterSpacing: 1,
  },
});