import { StyleSheet } from "react-native";

export default StyleSheet.create({
  container: { flex: 1 },
  scrollContent: {
    padding: 24,
    paddingTop: 80,
    paddingBottom: 60,
    flexGrow: 1,
  },
  header: { alignItems: "center", marginBottom: 40 },
  logo: {
    fontSize: 48,
    fontWeight: "900",
    color: "#22c55e",
    letterSpacing: 2,
    marginBottom: 8,
  },
  subtitle: {
    fontSize: 18,
    color: "#94a3b8",
    fontWeight: "500",
  },
  title: {
    fontSize: 32,
    fontWeight: "800",
    color: "#fff",
    textAlign: "center",
    marginBottom: 40,
  },
  inputGroup: { marginBottom: 24 },
  label: {
    color: "#94a3b8",
    fontSize: 14,
    fontWeight: "600",
    marginBottom: 8,
    marginLeft: 4,
    textTransform: "uppercase",
    letterSpacing: 1.2,
  },
  input: {
    backgroundColor: "rgba(255,255,255,0.1)",
    borderRadius: 16,
    padding: 18,
    fontSize: 17,
    color: "#fff",
    borderWidth: 1,
    borderColor: "rgba(34,197,94,0.3)",
  },
  bioInput: { height: 110, paddingTop: 18 },
  finishBtn: {
    backgroundColor: "#22c55e",
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    paddingVertical: 20,
    borderRadius: 30,
    marginTop: 30,
    shadowColor: "#22c55e",
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.6,
    shadowRadius: 20,
    elevation: 15,
  },
  finishText: {
    color: "#fff",
    fontSize: 20,
    fontWeight: "bold",
    letterSpacing: 1,
  },
  footerText: {
    textAlign: "center",
    marginTop: 30,
    color: "#64748b",
    fontSize: 15,
    fontStyle: "italic",
  },
});